### ISSUE TITLE
How stable is the project

### ISSUE THREAD

**Issue by HeaTTheatR** [asyncgui/asynckivy#117]
Hi!
I want to add your package as a dependency to the `KivyMD` library. How can we use this package in the `install_requires` file `setup.py`:

```
python
    setup(
        ...
        install_requires=["kivy>=2.0.0", "pillow", "materialyoucolor", "asynckivy"],
        ...
    )
```

Will that be right?
Thanks!

**Comment by kengoon** [comment]
Nice move 👍
